name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: get pg_container
      run: docker pull postgres
    - name: run container
      run: docker run --publish 5432:5432 --detach --name postsql1 -e POSTGRES_PASSWORD=eJNhKFwEYfkm -d postgres
    - name: Test
      run: dotnet test --no-restore --verbosity normal

